(clear)
(load "ControlSemana.clp")
(load "DCasa.clp")
(load "RCasa.clp")
(load "DSensores.clp")
(load "MHumedad.clp")
(load "MIniciarUbicacion.clp")
(load "MLecturaSensores.clp")
(load "MLuminosidad.clp")
(load "MMagnetico.clp")
(load "MMovimiento.clp")
(load "MUbicacion.clp")
(load "MVarios.clp")
(reset)
(run 60)

